[package]
name = "rusttracer"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
derive-new = "0.5.8"
byteorder = "1.5.0"
stb_image = "0.3.0"
lazy_static = "1.5.0"
rand_xorshift = "0.4.0"
nalgebra = "0.34.1"
